// src/pages/substitutions.vue
<template>
	<div>
		<h1>Substitutions</h1>
		<div v-if="success" class="panel--success">
			<p>Substitution submitted successfully.</p>
		</div>
		<div v-else-if="error" class="panel--error">
			<p>
				An error occurred: Submission was marked as spam. Please email
				<a href="mailto:info@bluemoonorganics.com">info@bluemoonorganics.com</a>
				directly.
			</p>
		</div>
		<form v-else>
			<label for="fullName">Full name*</label>
			<input
				placeholder="John Appleseed"
				v-model="fullName"
				type="text"
				name="fullName"
				required
			/>

			<label for="phone">Phone number*</label>
			<input
				placeholder="123-123-1234"
				v-model="phone"
				type="tel"
				name="phone"
				required
			/>

			<label for="address1">Address - line 1*</label>
			<input
				placeholder="502 Infinite Way"
				v-model="address1"
				type="text"
				name="address1"
				required
			/>

			<label for="address2">Address - line 2</label>
			<input
				placeholder="Unit 15"
				v-model="address2"
				type="text"
				name="address2"
			/>

			<label for="city">City*</label>
			<input
				placeholder="Coquitlam"
				v-model="city"
				type="text"
				name="city"
				required
			/>

			<label for="email">Email address*</label>
			<input
				placeholder="john@appleseed.com"
				v-model="email"
				type="email"
				name="email"
				required
			/>

			<label for="deliveryDay">Delivery day*</label>
			<input
				placeholder="Monday"
				v-model="deliveryDay"
				type="text"
				name="deliveryDay"
				required
			/>

			<label>Box type*</label>
			<input
				id="regularBox"
				type="radio"
				name="boxType"
				value="Regular box"
				required
				v-model="boxType"
			/>
			<label class="radio" for="regularBox">Regular box</label>

			<input
				id="fruitBox"
				type="radio"
				name="boxType"
				v-model="boxType"
				value="Fruit box"
			/>
			<label class="radio" for="fruitBox">Fruit box</label>

			<label for="itemsToRemove">Items to remove</label>
			<textarea v-model="itemsToRemove" name="itemsToRemove" />

			<label for="itemsToAdd">Items to add</label>
			<textarea v-model="itemsToAdd" name="itemsToAdd" />

			<label for="comments">Comments</label>
			<textarea v-model="comments" name="comments" />

			<!-- the following input is a honeypot -->
			<p id="captcha">
				If you're human, don't fill this out:
				<input type="text" v-model="captcha" />
			</p>

			<button @click="submit" type="submit">Submit</button>
		</form>
	</div>
</template>
<script>
export default {
	methods: {
		submit() {
			event.preventDefault();
			console.log("Submitting...");
			let data = {
				type: "Substitution",
				fullName: this.fullName,
				phone: this.phone,
				email: this.email,
				address1: this.address1,
				address2: this.address2,
				city: this.city,
				deliveryDay: this.deliveryDay,
				boxType: this.boxType,
				itemsToRemove: this.itemsToRemove,
				itemsToAdd: this.itemsToAdd,
				comments: this.comments,
				captcha: this.captcha
			};
			fetch(".netlify/functions/sendEmail", {
				method: "POST",
				headers: {
					"Content-Type": "application/json"
				},
				body: JSON.stringify(data)
			})
				.then(response => {
					if (response.status == 200) {
						this.success = true;
					} else {
						if (response.status == 400) {
							this.error = true;
						}
					}
				})
				.catch(error => {
					console.error(error);
				});
		}
	},
	data() {
		return {
			fullName: "",
			phone: "",
			email: "",
			address1: "",
			address2: "",
			city: "",
			deliveryDay: "",
			boxType: "",
			itemsToRemove: "",
			itemsToAdd: "",
			comments: "",
			captcha: "",
			success: false,
			error: false
		};
	}
};
</script>

// pages/substitutions.tsx
import { useState } from "react";
import { getDeliveryAreas } from "../lib/api";
import fs from "fs";
import matter from "gray-matter";
import html from "remark-html";
import { remark } from "remark";
import { rehype } from "rehype";
import rehypeSlug from "rehype-slug";
import { parse } from 'node-html-parser';

const getBoxContent = (htmlContent, boxId) => {
  try {
    const htmlDoc = parse(htmlContent.toString());
    const box = htmlDoc.getElementById(boxId).nextElementSibling;
    return box.outerHTML
  } catch (error) {
    return null;
  }
};

export async function getStaticProps() {
  const file = fs.readFileSync(`content/pages/index.md`, "utf8");
  const { content } = matter(file);
  const processedContent = await remark().use(html).process(content);
  const htmlContent = (
    await rehype().use(rehypeSlug).process(processedContent)
  ).toString();
  return {
    props: {
      deliveryAreas: getDeliveryAreas(),
      regular: getBoxContent(htmlContent, "regular-box-4200"),
      fruit: getBoxContent(htmlContent, "fruit-box-4200"),
      extras: getBoxContent(htmlContent, "extras"),
    },
  };
}

export default function Substitutions({
  deliveryAreas,
  regular,
  fruit,
  extras,
}) {
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(false);
  const [formData, setFormData] = useState({
    type: "Substitution",
    fullName: "",
    phone: "",
    email: "",
    address1: "",
    address2: "",
    city: "",
    deliveryDay: "",
    boxType: "",
    itemsToRemove: "",
    itemsToAdd: "",
    comments: "",
    captcha: "",
  });

  const handleSubmit = async (event) => {
    event.preventDefault();
    const response = await fetch("/api/submission", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(formData),
    });
    if (response.ok) {
      setSuccess(true);
      setError(false);
    } else {
      setSuccess(false);
      setError(true);
    }
  };

  const handleInputChange = (event) => {
    const target = event.target;
    const name = target.name;
    const value = target.value;

    setFormData({
      ...formData,
      [name]: value,
    });
  };

  return (
    <div>
      <h1>Substitutions</h1>

      {regular && fruit && extras && (
        <div id="extras-specials">
          <div>
            <h3>Regular Box</h3>
            <div dangerouslySetInnerHTML={{ __html: regular }} />
          </div>
          <div>
            <h3>Fruit Box</h3>
            <div dangerouslySetInnerHTML={{ __html: fruit }} />
          </div>
          <div>
            <h3>Extras</h3>
            <div dangerouslySetInnerHTML={{ __html: extras }} />
          </div>
        </div>
      )}
      {success && (
        <div className="panel--success">
          <p>Substitution submitted successfully.</p>
        </div>
      )}
      {error && (
        <div className="panel--error">
          <p>
            An error occurred: Submission was marked as spam. Please email{" "}
            <a href="mailto:info@bluemoonorganics.com">
              info@bluemoonorganics.com
            </a>{" "}
            directly.
          </p>
        </div>
      )}
      {!success && !error && (
        <form onSubmit={handleSubmit}>
          <label htmlFor="fullName">Full name*</label>
          <input
            type="text"
            name="fullName"
            id="fullName"
            placeholder="John Appleseed"
            required
            value={formData.fullName}
            onChange={handleInputChange}
          />

          <label htmlFor="phone">Phone number*</label>
          <input
            onChange={handleInputChange}
            value={formData.phone}
            placeholder="123-123-1234"
            type="tel"
            name="phone"
            required
          />

          <label htmlFor="address1">Address - line 1*</label>
          <input
            onChange={handleInputChange}
            value={formData.address1}
            placeholder="502 Infinite Way"
            type="text"
            name="address1"
            required
          />

          <label htmlFor="address2">Address - line 2</label>
          <input
            onChange={handleInputChange}
            value={formData.address2}
            placeholder="Unit 15"
            type="text"
            name="address2"
          />

          <label htmlFor="city">City*</label>
          <input
            onChange={handleInputChange}
            value={formData.city}
            placeholder="Coquitlam"
            type="text"
            name="city"
            required
          />

          <label htmlFor="email">Email address*</label>
          <input
            onChange={handleInputChange}
            value={formData.email}
            placeholder="john@appleseed.com"
            type="email"
            name="email"
            required
          />

          <label htmlFor="deliveryDay">Delivery day*</label>
          <input
            onChange={handleInputChange}
            value={formData.deliveryDay}
            placeholder="Monday"
            type="text"
            name="deliveryDay"
            required
          />

          <label>Box type*</label>
          <input
            id="regularBox"
            onChange={handleInputChange}
            checked={formData.boxType === "Regular box"}
            type="radio"
            name="boxType"
            value="Regular box"
            required
          />
          <label className="radio" htmlFor="regularBox">
            Regular box
          </label>

          <input
            id="fruitBox"
            onChange={handleInputChange}
            checked={formData.boxType === "Fruit box"}
            type="radio"
            name="boxType"
            value="Fruit box"
          />
          <label className="radio" htmlFor="fruitBox">
            Fruit box
          </label>

          <label htmlFor="itemsToRemove">Items to remove</label>
          <textarea
            onChange={handleInputChange}
            value={formData.itemsToRemove}
            name="itemsToRemove"
          />

          <label htmlFor="itemsToAdd">Items to add</label>
          <textarea
            onChange={handleInputChange}
            value={formData.itemsToAdd}
            name="itemsToAdd"
          />

          <label htmlFor="comments">Comments</label>
          <textarea
            onChange={handleInputChange}
            value={formData.comments}
            name="comments"
          />

          {/* the following input is a honeypot */}
          <p id="captcha">
            If you're human, don't fill this out:
            <input
              onChange={handleInputChange}
              value={formData.captcha}
              type="text"
            />
          </p>

          <button>Submit</button>
        </form>
      )}
    </div>
  );
}
